---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cicd-app
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: helm-chart
      sourceRef:
        kind: GitRepository
        name: cicd-app
        namespace: flux-system
        secretRef:
          name: git-ssh-key-secret # Name of the secret you created
      interval: 1m
  