---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cicd-app
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: cicd-app
        